server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://krcoguptjfxlou:57a24c8bccbbeffafb14fb2f94ac1c74037e36a6cb7c3a3cdf330f7a38f1a377@ec2-52-23-40-80.compute-1.amazonaws.com:5432/de746svvqhj5pp
    username: krcoguptjfxlou
    password: 57a24c8bccbbeffafb14fb2f94ac1c74037e36a6cb7c3a3cdf330f7a38f1a377
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santader  / Backend
